#!/bin/sh
cd /home/kevin/apps/pomandhoney
npm install
pm2 restart 0
echo "*******************************************"
echo "Server has been updated."
echo "*******************************************"
